# Generated by Django 3.1.5 on 2021-03-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodidea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
