# Generated by Django 3.1.5 on 2021-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodidea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
